permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      isHome: false
      isPost: false
  -
    scope:
      path: ""
      types: [posts, drafts]
    values:
      layout: post
      isHome: false
      isPost: true

kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-coffeescript
  - jekyll-paginate

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
