permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      isHome: false
      isPost: false
  -
    scope:
      path: ""
      types: [posts, drafts]
    values:
      layout: post
      isHome: false
      isPost: true

markdown: redcarpet

redcarpet:
  extensions:
    - space_after_headers
    - underline
    - strikethrough
    - highlight
