permalink: /:title/
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      isPost: false
  -
    scope:
      path: ""
      types: [posts, drafts]
    values:
      layout: post
      isPost: true
